name: FastAPI CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        echo "No tests implemented yet"
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.nitesh232003 }}
        password: ${{ secrets.niteshpassword }}

    
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.nitesh232003 }}/fastapi-app:latest ./backend

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.nitesh232003 }}/fastapi-app:latest
      
    
    - name: Pull Image From Registry
      run: |
        docker pull ${{ secrets.nitesh232003 }}/fastapi-app:latest

    - name: Run Container
      run: |
        docker run -d -p 8000:8000 ${{ secrets.nitesh232003 }}/fastapi-app:latest